server:
  port: 80

app: 
  logging-to: console # options are: console / file
  drone: 
    video-ws-endpoint: /videofeed # video websocket endpoint
    video-server-port: 1315 # port where were listening and receiving udp packages
    control-server-port: 1314 # listening for connection in TCP from raspi
    drone-id-length: 1 # One byte size for the drone ID, this is number of symbols
    default-altitude: 4
    default-speed: 15

logging: 
  level:
    org.springframework: INFO
    com.odafa.cloudapp: DEBUG